import json

from packages.model_client import ModelClient
from packages.tools import TOOL_DEFINITIONS, run_tool, tool_result_to_json


def print_section(title: str) -> None:
    """打印分隔标题。"""

    print(f"\n=== {title} ===")


def parse_tool_arguments(arguments: str) -> dict:
    """解析模型返回的工具调用参数。"""

    if not arguments:
        return {}

    return json.loads(arguments)


def main() -> None:
    model_client = ModelClient()

    user_request = "请帮我把“做一个 AI 学习助手”拆解成项目任务清单。"

    messages = [
        {
            "role": "user",
            "content": user_request,
        }
    ]

    print_section("User Request")
    print(user_request)

    print_section("Step 1: Model decides whether to call tools")

    first_response = model_client.client.chat.completions.create(
        model=model_client.pro_model,
        messages=messages,
        tools=TOOL_DEFINITIONS,
        tool_choice="auto",
        temperature=0.2,
    )

    assistant_message = first_response.choices[0].message

    print("Assistant message content:")
    print(assistant_message.content)

    if not assistant_message.tool_calls:
        print("\nNo tool call generated by model.")
        return

    print("\nTool calls:")
    for tool_call in assistant_message.tool_calls:
        print(f"- id: {tool_call.id}")
        print(f"  name: {tool_call.function.name}")
        print(f"  arguments: {tool_call.function.arguments}")

    messages.append(assistant_message)

    print_section("Step 2: Program runs local tools")

    for tool_call in assistant_message.tool_calls:
        tool_name = tool_call.function.name
        arguments = parse_tool_arguments(tool_call.function.arguments)

        print(f"Running tool: {tool_name}")
        print(f"Arguments: {arguments}")

        tool_result = run_tool(tool_name, arguments)
        tool_result_json = tool_result_to_json(tool_result)

        print("Tool result:")
        print(tool_result_json)

        messages.append(
            {
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": tool_result_json,
            }
        )

    print_section("Step 3: Model generates final answer based on tool result")

    final_response = model_client.client.chat.completions.create(
        model=model_client.flash_model,
        messages=messages,
        temperature=0.3,
    )

    final_message = final_response.choices[0].message

    print(final_message.content)


if __name__ == "__main__":
    main()